In [25]:
#Reseau de neurones pour identification de locuteur
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

Base_train = np.genfromtxt('Base_train.dat', dtype=None)
Base_test = np.genfromtxt('Base_test.dat', dtype=None)
Label_train = np.genfromtxt('Label_train.dat', dtype=None)
#Les ex sont en lignes (12ou85x16) (train_ou_test)

#Définition de l'Architecture:
#on utilise 2 couches et un noeud en sortie
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(5,input_shape=(21,), activation='relu'))
model.add(Dense(5, activation='relu'))
model.add(Dense(1))

model.summary()

model.compile(loss='mse',optimizer='adam')
model.fit(Base_train,Label_train, batch_size=1,epochs=30)


Model: "sequential_11"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_32 (Dense)             (None, 3)                 66        
_________________________________________________________________
dense_33 (Dense)             (None, 2)                 8         
_________________________________________________________________
dense_34 (Dense)             (None, 1)                 3         
Total params: 77
Trainable params: 77
Non-trainable params: 0
_________________________________________________________________
Train on 39 samples
Epoch 1/30
39/39 [==============================] - 0s 12ms/sample - loss: 0.2937
Epoch 2/30
39/39 [==============================] - 0s 2ms/sample - loss: 0.2379
Epoch 3/30
39/39 [==============================] - 0s 2ms/sample - loss: 0.1675
Epoch 4/30
39/39 [==============================] - 0s 2ms/sample - loss: 0.1390
Epoch 5/30
39/39 [========================

In [27]:
predictions = model.predict(Base_test)
predictions[1:4]

array([[0.657242  ],
       [0.7251189 ],
       [0.00170501]], dtype=float32)

In [17]:
predictions[4:16]

array([[ 0.70696104],
       [ 0.6232128 ],
       [ 0.24273628],
       [ 0.23219913],
       [ 0.23917863],
       [ 0.65837264],
       [ 0.7333089 ],
       [ 0.84506947],
       [ 0.26702875],
       [ 0.411911  ],
       [-0.04022688],
       [ 0.02557342]], dtype=float32)

In [18]:
predictions[16:]

array([[ 9.6685797e-02],
       [ 2.5503993e-02],
       [ 4.3410766e-01],
       [ 2.9389226e-01],
       [ 4.0017545e-01],
       [-4.9468517e-02],
       [-6.2460147e-02],
       [-3.4064054e-04],
       [ 3.6097026e-01],
       [ 3.6552632e-01],
       [ 3.9907056e-01],
       [ 2.7287167e-01],
       [ 3.1268477e-01],
       [ 3.9198428e-02],
       [-1.6439214e-02],
       [ 1.9688696e-01],
       [-1.2997091e-03]], dtype=float32)